"""Mihomo subscription proxy configuration and per-platform routing."""
import json
import os
from pathlib import Path
from typing import Any, Optional

import httpx
from app.config_manager import get_effective_config


def _enabled(value: Any) -> bool:
    return str(value or "").lower() in {"1", "true", "yes", "on"}


def platform_proxy_url(platform: Optional[str] = None) -> Optional[str]:
    config = get_effective_config("proxy")
    if not _enabled(config.get("enabled")):
        return None
    route = get_effective_config("fetch_routing").get(platform or "")
    if route != "proxy" and platform not in {"x", "youtube", "github"}:
        return None
    return (config.get("proxy_url") or "").strip() or None


def playwright_proxy(platform: Optional[str] = None) -> Optional[dict]:
    from urllib.parse import urlparse
    raw = platform_proxy_url(platform)
    if not raw:
        return None
    parsed = urlparse(raw)
    server = f"{parsed.scheme or 'http'}://{parsed.hostname}" + (f":{parsed.port}" if parsed.port else "")
    result = {"server": server}
    if parsed.username:
        result["username"] = parsed.username
    if parsed.password:
        result["password"] = parsed.password
    return result


def _mihomo_yaml(config: dict) -> str:
    url = (config.get("subscription_url") or "").strip()
    secret = os.getenv("MIHOMO_CONTROLLER_SECRET", "")
    return f"""# Generated by Trove AI. Edit the subscription in System Management.
mixed-port: 7890
allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: {json.dumps(secret)}
profile:
  store-selected: true
  store-fake-ip: true
proxy-providers:
  trove-subscription:
    type: http
    url: {json.dumps(url)}
    path: ./providers/trove-subscription.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: TROVE_PROXY
    type: url-test
    use: [trove-subscription]
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 100
rules:
  - MATCH,TROVE_PROXY
"""


async def test_proxy_connection(config: Optional[dict] = None) -> dict:
    config = config or get_effective_config("proxy")
    if not _enabled(config.get("enabled")):
        return {"ok": True, "message": "代理已关闭"}
    url = (config.get("subscription_url") or "").strip()
    if not url:
        return {"ok": False, "error": "启用代理前请填写 Clash 订阅地址"}
    try:
        async with httpx.AsyncClient(timeout=20, follow_redirects=True, trust_env=False) as client:
            response = await client.get(url, headers={"User-Agent": "mihomo/1.19 TroveAI/1.3"})
        response.raise_for_status()
        if len(response.text.strip()) < 20:
            return {"ok": False, "error": "订阅响应为空或内容过短"}
        return {"ok": True, "message": "订阅地址可访问"}
    except Exception as exc:
        return {"ok": False, "error": f"订阅访问失败：{type(exc).__name__}"}


async def apply_proxy_config(config: Optional[dict] = None) -> dict:
    config = config or get_effective_config("proxy")
    if not _enabled(config.get("enabled")):
        return {"ok": True, "message": "代理未启用，无需应用"}
    path = Path(os.getenv("MIHOMO_CONFIG_PATH", "/tmp/trove-mihomo/config.yaml"))
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".yaml.tmp")
    temporary.write_text(_mihomo_yaml(config), encoding="utf-8")
    temporary.replace(path)
    controller = (config.get("controller_url") or "http://mihomo:9090").rstrip("/")
    headers = {}
    secret = os.getenv("MIHOMO_CONTROLLER_SECRET", "")
    if secret:
        headers["Authorization"] = f"Bearer {secret}"
    try:
        async with httpx.AsyncClient(timeout=10, trust_env=False) as client:
            response = await client.put(
                f"{controller}/configs?force=true", headers=headers,
                json={"path": os.getenv("MIHOMO_CONTAINER_CONFIG_PATH", "/root/.config/mihomo/config.yaml")},
            )
        response.raise_for_status()
    except Exception as exc:
        return {"ok": False, "error": f"配置已生成，但 Mihomo 重载失败：{type(exc).__name__}"}
    return {"ok": True, "message": "Mihomo 配置已更新并热重载"}
